require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FiliaisController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Filial. As you add validations to Filial, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FiliaisController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all filiais as @filiais" do
      filial = Filial.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:filiais)).to eq([filial])
    end
  end

  describe "GET show" do
    it "assigns the requested filial as @filial" do
      filial = Filial.create! valid_attributes
      get :show, {:id => filial.to_param}, valid_session
      expect(assigns(:filial)).to eq(filial)
    end
  end

  describe "GET new" do
    it "assigns a new filial as @filial" do
      get :new, {}, valid_session
      expect(assigns(:filial)).to be_a_new(Filial)
    end
  end

  describe "GET edit" do
    it "assigns the requested filial as @filial" do
      filial = Filial.create! valid_attributes
      get :edit, {:id => filial.to_param}, valid_session
      expect(assigns(:filial)).to eq(filial)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Filial" do
        expect {
          post :create, {:filial => valid_attributes}, valid_session
        }.to change(Filial, :count).by(1)
      end

      it "assigns a newly created filial as @filial" do
        post :create, {:filial => valid_attributes}, valid_session
        expect(assigns(:filial)).to be_a(Filial)
        expect(assigns(:filial)).to be_persisted
      end

      it "redirects to the created filial" do
        post :create, {:filial => valid_attributes}, valid_session
        expect(response).to redirect_to(Filial.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved filial as @filial" do
        post :create, {:filial => invalid_attributes}, valid_session
        expect(assigns(:filial)).to be_a_new(Filial)
      end

      it "re-renders the 'new' template" do
        post :create, {:filial => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested filial" do
        filial = Filial.create! valid_attributes
        put :update, {:id => filial.to_param, :filial => new_attributes}, valid_session
        filial.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested filial as @filial" do
        filial = Filial.create! valid_attributes
        put :update, {:id => filial.to_param, :filial => valid_attributes}, valid_session
        expect(assigns(:filial)).to eq(filial)
      end

      it "redirects to the filial" do
        filial = Filial.create! valid_attributes
        put :update, {:id => filial.to_param, :filial => valid_attributes}, valid_session
        expect(response).to redirect_to(filial)
      end
    end

    describe "with invalid params" do
      it "assigns the filial as @filial" do
        filial = Filial.create! valid_attributes
        put :update, {:id => filial.to_param, :filial => invalid_attributes}, valid_session
        expect(assigns(:filial)).to eq(filial)
      end

      it "re-renders the 'edit' template" do
        filial = Filial.create! valid_attributes
        put :update, {:id => filial.to_param, :filial => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested filial" do
      filial = Filial.create! valid_attributes
      expect {
        delete :destroy, {:id => filial.to_param}, valid_session
      }.to change(Filial, :count).by(-1)
    end

    it "redirects to the filiais list" do
      filial = Filial.create! valid_attributes
      delete :destroy, {:id => filial.to_param}, valid_session
      expect(response).to redirect_to(filiais_url)
    end
  end

end
